language: php
dist: trusty
sudo: false
services:
 - rabbitmq
 - mysql
 - postgresql
 - elasticsearch

php:
  - 7.1

addons:
  firefox: "51.0.1"
  apt:
    packages:
      - nginx
      - realpath

cache:
  directories:
  - $HOME/.composer/cache/files

matrix:
  exclude:
    - php: 7.1
  include:
    - php: 7.1
      env: LINTS=true COMPOSER_CHANNEL=stable
    - php: 7.1
      env: RELEASE=stable COMPOSER_CHANNEL=stable

before_install:
  - /bin/bash -xe travis/before-install.sh

install:
  - /bin/bash -xe travis/install.sh

script:
  - /bin/bash -xe travis/test-script.sh
